### ISSUE TITLE
Project Portfolio: application deploy

### ISSUE THREAD

**Issue by tan12082001** [tan12082001/Project-portfolio#7]
Microverse Module-1 Week-3
Project Portfolio: Application Deploy
For this project, I need to create a new pull request by updating the README with deployed portfolio website using the GitHub pages. but as I have already included the Live demo link in the README file I am creating this issue for the code review.
* Link for the Portfolio Website from GitHub Pages: https://tan12082001.github.io/Project-portfolio/

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @tan12082001 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- The website is deployed using GitHub pages ✔
- README is properly updated with demo link  ✔
- Descriptive issue title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
